In [22]:
#upper right diagonal

import numpy as np

sims = 5
timesteps = (1, 0.99, 0.97, 0.95)

MC = np.zeros((sims, len(timesteps), len(timesteps)))


for i in range(sims):
    for j in range(len(timesteps)):
        for k in range(j, len(timesteps)):
           MC[i, j, k] = timesteps[k]

print(MC)

[[[1.   0.99 0.97 0.95]
  [0.   0.99 0.97 0.95]
  [0.   0.   0.97 0.95]
  [0.   0.   0.   0.95]]

 [[1.   0.99 0.97 0.95]
  [0.   0.99 0.97 0.95]
  [0.   0.   0.97 0.95]
  [0.   0.   0.   0.95]]

 [[1.   0.99 0.97 0.95]
  [0.   0.99 0.97 0.95]
  [0.   0.   0.97 0.95]
  [0.   0.   0.   0.95]]

 [[1.   0.99 0.97 0.95]
  [0.   0.99 0.97 0.95]
  [0.   0.   0.97 0.95]
  [0.   0.   0.   0.95]]

 [[1.   0.99 0.97 0.95]
  [0.   0.99 0.97 0.95]
  [0.   0.   0.97 0.95]
  [0.   0.   0.   0.95]]]


In [24]:
#bottom left  diagonal

import numpy as np

sims = 5
timesteps = (1, 0.99, 0.97, 0.95)

MC = np.zeros((sims, len(timesteps), len(timesteps)))


for i in range(sims):
    for j in range(len(timesteps)):
        for k in range(j+1):
           MC[i, j, k] = timesteps[k]

print(MC)

[[[1.   0.   0.   0.  ]
  [1.   0.99 0.   0.  ]
  [1.   0.99 0.97 0.  ]
  [1.   0.99 0.97 0.95]]

 [[1.   0.   0.   0.  ]
  [1.   0.99 0.   0.  ]
  [1.   0.99 0.97 0.  ]
  [1.   0.99 0.97 0.95]]

 [[1.   0.   0.   0.  ]
  [1.   0.99 0.   0.  ]
  [1.   0.99 0.97 0.  ]
  [1.   0.99 0.97 0.95]]

 [[1.   0.   0.   0.  ]
  [1.   0.99 0.   0.  ]
  [1.   0.99 0.97 0.  ]
  [1.   0.99 0.97 0.95]]

 [[1.   0.   0.   0.  ]
  [1.   0.99 0.   0.  ]
  [1.   0.99 0.97 0.  ]
  [1.   0.99 0.97 0.95]]]
