In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('usd_curve_basic.csv')
times = data['t'].values
df0 = data['df'].values
sims = 5
timesteps = 5 
x0 = 0
a = 0.1
sig = 0.02

#print(df0)

def hw_exp(a, x, t1, t2):
    return x * np.exp(-a * (t2 - t1))

def hw_var(a, sig, t1, t2):
    return sig ** 2 * (1 - np.exp(-2 * a * (t2 - t1))) / (2 * a)

x = np.zeros((sims, timesteps))
    
for i in range(sims):
    x[i,0] = x0
    for j in range(1, timesteps):
        Z1 = np.random.normal(0,1)
        x[i,j] = hw_exp(a, x[i,j-1], j-1, j) + Z1 * (hw_var(a, sig, j-1, j) ** 0.5) # possible need a rt time in here
            
print(x)

[[ 0.         -0.01363752 -0.00012551  0.03128666 -0.00409036]
 [ 0.          0.00873456 -0.00993702 -0.02290479 -0.0235497 ]
 [ 0.          0.04826115  0.01956015  0.05207341  0.03786427]
 [ 0.         -0.00359945 -0.01108904 -0.01528999 -0.01629752]
 [ 0.         -0.01057263  0.00581967  0.00468881  0.02283823]]


In [4]:
# discount factors
# j is one timestep before point we are calculating - THIS MIGHT NEED CORRECTING

def cov(sig, i, j):
    return sig ** 2 * (np.exp(-a * abs(j - i)) - np.exp(-a * (j + i))) / (2 * a)

def q(a, i, j):
    return (1 - np.exp(-a * (j - i))) / a

def phi(sig, j):
    phi = 0
    for i in range(j - 1):
        phi += q(i) * cov(sig, i, j)
    return phi
    
def gamma(j):
    return 0.5 * cov(j, j)
    
def hwdf(t, T, x, a, sig):
    B_tn = self.interpolated_df(t, times, df0)
    B_T = self.interpolated_df(T, times, df0)
    if t == 0:
        discount_factor = B_T / B_tn 
    else:
        discount_factor = (B_T / B_tn) * np.exp(- (x + phi(sig, t)) * q(t, T) - (gamma(t) * q(t, T) ** 2) )
    

In [19]:
for i in range(sims):
    for j in range(timesteps):
        for k in range(timesteps):


1.0