In [13]:
import pandas as pd
import numpy as np

days = 252

periods = 5
Nums = periods 
sim = 5
fwd = np.zeros((sim, Nums, periods))
Dev = np.zeros((sim, Nums))
Timestep = np.zeros(periods + 1)
correl = np.zeros(periods + 1)
fwdvol = np.zeros(periods + 1)
Notional = np.zeros(periods + 1)
fixed_rate = np.zeros(periods + 1)
df = np.zeros((sim, Nums, periods + 1))
MtM = np.zeros((sim, periods))
sumfxd = 0
sumflt = 0
Orgsumfxd = 0
Orgsumflt = 0


for k in range(periods + 1):
    Timestep[k] = 1
    correl[k] = 1
    fwdvol[k] = 0.2
    fixed_rate[k]= 0.01
    Notional[k] = 1000000
    
#print(Timestep)


for i in range(sim):
    df[i, 0, 0] = 1
    j = 0
    for k in range(periods):
        fwd[i, 0, k] = 0.02 + k * 0.001
        df[i, j, k + 1] = np.exp(-fwd[i, j, k] * Timestep[k]) * df[i, j, k]
        Orgsumfxd += Notional[k] * fixed_rate[k] * df[i, j, k + 1]
        Orgsumflt += Notional[k] * fwd[i, j, k] * df[i, j, k + 1]

    #print(OrgSumFxd)
    #print(OrgSumFlt)

    for j in range(1, periods):
        drift = 0    
        for k in range(j, periods):
            Z1 = np.random.normal(0,1)
            drift += (Timestep[k-1] * fwd[i, j-1, k] * fwdvol[j] * correl[k-1]) / (1 + fwd[i, j-1, k] * Timestep[k-1]) 
            fwd[i, j, k] = fwd[i, j-1, k] * np.exp((drift * fwdvol[k-1] - 0.5 * fwdvol[k-1] ** 2) * Timestep[k-1] + fwdvol[k-1] * Timestep[k-1] ** 0.5 * Z1)
            df[i, j, j] = 1
            df[i, j, k + 1] = np.exp(fwd[i, j, k] * Timestep[k]) * df[i, j, k]
            
            sumfxd += Timestep[k] * Notional[k] * fixed_rate[k] * df[i, j, k + 1]
            sumflt += Timestep[k] * Notional[k] * fwd[i, j, k] * df[i, j, k + 1]
            
        MtM[i, j] = sumfxd + sumflt
    
print(df)
#print(fwd)

#these shouldnt be 1's

[[[1.         0.98019867 0.95982913 0.93894347 0.91759423 0.89583414]
  [0.         1.         1.01870213 1.04477121 1.07302289 1.09849042]
  [0.         0.         1.         1.02883109 1.05107061 1.07556111]
  [0.         0.         0.         1.         1.02398725 1.04577937]
  [0.         0.         0.         0.         1.         1.02132682]]

 [[1.         0.98019867 0.95982913 0.93894347 0.91759423 0.89583414]
  [0.         1.         1.01859494 1.04459222 1.06882242 1.09075835]
  [0.         0.         1.         1.02539143 1.05222558 1.07292777]
  [0.         0.         0.         1.         1.02162463 1.03866835]
  [0.         0.         0.         0.         1.         1.02076611]]

 [[1.         0.98019867 0.95982913 0.93894347 0.91759423 0.89583414]
  [0.         1.         1.02106891 1.03814491 1.07075395 1.09763045]
  [0.         0.         1.         1.0188384  1.04576493 1.07457879]
  [0.         0.         0.         1.         1.01978135 1.05989578]
  [0.         0.

[[    0.         97370.33017611 67694.6738257  49119.43053822
  18983.61009961]]
149945.82461598358


Simulation 1:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]

Simulation 2:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]

Simulation 3:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]



In [4]:
import os
current_path = os.getcwd()
print(current_path)

C:\Users\Laptop\pricing_models
