In [7]:
#basic CVA modelling

import numpy as np
import matplotlib.pyplot as plt

#valuation function 

Forward = 100

#simulate underlying 

def MC(spot, vol, drift, sims, timesteps):
    MC = np.zeros((sims, timesteps))
    for i in range(sims):
        for j in range(timesteps):
            if j == 0:
                MC[i,j] = spot
            else:
                MC[i,j] = MC[i, j -1] * 2

    return MC

print(MC(100, 0.2, 0.02, 10, 5))


"""
class Scen_gen():
    def __init__(self, spot, drift, vol):
        self.spot = spot
        self.drift = drift
        self.vol = vol
        
    #def LV(self, s, t):               
    
    def MC(self, sims, timesteps, dt):
        x = np.zeros((sims, timesteps + 1))
        for i in range(sims):
            for j in range(timesteps + 1):
                z1 = np.random.normal(0, 1)
                if j == 0:
                    x[i, j] = self.spot  
                else:
                    x[i, j] = x[i, j - 1] * np.exp((self.drift - 0.5 * self.vol ** 2) * dt + (self.vol * dt ** 0.5 * z1))
        return x

"""

[[ 100.  200.  400.  800. 1600.]
 [ 100.  200.  400.  800. 1600.]
 [ 100.  200.  400.  800. 1600.]
 [ 100.  200.  400.  800. 1600.]
 [ 100.  200.  400.  800. 1600.]
 [ 100.  200.  400.  800. 1600.]
 [ 100.  200.  400.  800. 1600.]
 [ 100.  200.  400.  800. 1600.]
 [ 100.  200.  400.  800. 1600.]
 [ 100.  200.  400.  800. 1600.]]


'\nclass Scen_gen():\n    def __init__(self, spot, drift, vol):\n        self.spot = spot\n        self.drift = drift\n        self.vol = vol\n        \n    #def LV(self, s, t):               \n    \n    def MC(self, sims, timesteps, dt):\n        x = np.zeros((sims, timesteps + 1))\n        for i in range(sims):\n            for j in range(timesteps + 1):\n                z1 = np.random.normal(0, 1)\n                if j == 0:\n                    x[i, j] = self.spot  \n                else:\n                    x[i, j] = x[i, j - 1] * np.exp((self.drift - 0.5 * self.vol ** 2) * dt + (self.vol * dt ** 0.5 * z1))\n        return x\n\n'

array([-0.03491325, -0.0116061 ,  0.01240868, -0.00517319, -0.02057375])

In [10]:
import numpy as np
import matplotlib.pyplot as plt

# Define Portfolio
notional_irs = 1e7  # Notional of IRS
fixed_rate_irs = 0.02  # Fixed rate of IRS
maturity_irs = 5  # Maturity of IRS in years

notional_swaption = 0  # Notional of Swaption
fixed_rate_swaption = 0.02  # Fixed rate of Swaption
maturity_swaption = 5  # Maturity of Swaption in years
exercise_time = 2  # Exercise time of Swaption in years

# Simulation Parameters
n_paths = 1000  # Number of simulated paths
n_steps = 50  # Number of time steps
dt = maturity_irs / n_steps  # Time step size
interest_rate_vol = 0.2  # Interest rate volatility

# Simulate Interest Rate Paths
r = np.zeros((n_steps, n_paths))
r[:, 0] = 0.02  # Initial interest rate
print(r)
for t in range(1, n_steps):
    dw = np.sqrt(dt) * np.random.normal(size=n_paths)
    dr = interest_rate_vol * dw
    r[t, :] = r[t-1, :] + dr

# Calculate Exposure for IRS and Swaption
exposure_irs = np.maximum(notional_irs * (r - fixed_rate_irs) * dt, 0)
exposure_swaption = np.maximum(
    notional_swaption * np.maximum(r[exercise_time, :] - fixed_rate_swaption, 0) * dt, 0)

# Calculate CVA
cva_irs = np.mean(np.sum(exposure_irs, axis=0))
cva_swaption = np.mean(exposure_swaption)

print("CVA for IRS:", cva_irs)
print("CVA for Swaption:", cva_swaption)


# Define the time points
time_points = np.linspace(0, maturity_irs, n_steps)

# Calculate Exposure for IRS and Swaption at each time point and each path
exposure_irs = np.maximum(notional_irs * (r - fixed_rate_irs) * dt, 0)
exposure_swaption = np.zeros_like(exposure_irs)
exposure_swaption[exercise_time:, :] = np.maximum(notional_swaption * (r[exercise_time:, :] - fixed_rate_swaption) * dt, 0)

# Calculate the total exposure of the portfolio at each time point and each path
total_exposure = exposure_irs + exposure_swaption

# Calculate EPE at each time point
epe = np.mean(np.maximum(total_exposure, 0), axis=1)

"""
# Plot EPE
plt.plot(time_points, epe, label='EPE')
plt.xlabel('Time (years)')
plt.ylabel('Expected Positive Exposure')
plt.title('Expected Positive Exposure of the Portfolio')
plt.legend()
plt.show()

"""

[[0.02 0.   0.   ... 0.   0.   0.  ]
 [0.02 0.   0.   ... 0.   0.   0.  ]
 [0.02 0.   0.   ... 0.   0.   0.  ]
 ...
 [0.02 0.   0.   ... 0.   0.   0.  ]
 [0.02 0.   0.   ... 0.   0.   0.  ]
 [0.02 0.   0.   ... 0.   0.   0.  ]]
CVA for IRS: 5381415.162654762
CVA for Swaption: 0.0


"\n# Plot EPE\nplt.plot(time_points, epe, label='EPE')\nplt.xlabel('Time (years)')\nplt.ylabel('Expected Positive Exposure')\nplt.title('Expected Positive Exposure of the Portfolio')\nplt.legend()\nplt.show()\n\n"

In [ ]:
import numpy as np

sims = 2
timesteps = 2
counter = 1

MC = np.zeros((sims, timesteps, counter))
print(MC)

for i in range(sims):
    for j in range(timesteps):
        for k in range(counter):
            counter += 1
            